development:
  dialect: postgres
  database: opsx
  user: postgres
  password: password
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:password@127.0.0.1:5432/webapp_test"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:password@127.0.0.1:5432/webapp_production"}}
